### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by bompi88** [bompi88/grand-view#27]
Remove all trashy code that came along. There is tab-support that should be removed, as well as other things. Try to move things inside their respective controllers, and generalize (not too much though).

**Comment by bompi88** [comment]
Use Mantrajs as a guideline. Update to ES2015 and meteor 1.3. Astronomy, Flowrouter and React.

**Comment by andreasdri** [comment]
Sounds like a total rewrite :stuck_out_tongue:

**Comment by bompi88** [comment]
Yes :smile:  and a great opportunity to learn ES6 and Mantra :+1:

**Comment by bompi88** [comment]
To general to be considered as an issue.
